import { createApp } from "file:///C:/Dev/washcut-project/apps/api/src/index.js";
const PORT = 4124, base = `http://localhost:${PORT}`;
const server = createApp().listen(PORT);
const login = async (e, p) => { const r = await fetch(base + "/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: e, password: p }) }); const j = await r.json(); return j.data.accessToken; };
const tok = await login("owner@kings.id", "demo1234");
const tokW = await login("owner@aquashine.id", "demo1234");
const H = { Authorization: `Bearer ${tok}`, "Content-Type": "application/json" };
const HW = { Authorization: `Bearer ${tokW}`, "Content-Type": "application/json" };
const j = (r) => r.json();
let r = await fetch(base + "/api/businesses/b1/services/s1", { method: "PATCH", headers: H, body: JSON.stringify({ price: 55000 }) });
console.log("PATCH service:", r.status, (await j(r)).ok);
r = await fetch(base + "/api/businesses/b1/services/s1", { method: "DELETE", headers: H });
console.log("DELETE service:", r.status, (await j(r)).ok);
r = await fetch(base + "/api/businesses/b1/services", { headers: H });
const list = (await j(r)).data;
console.log("s1 excluded after delete:", !list.some((s) => s.id === "s1"));
r = await fetch(base + "/api/businesses/b1/customers/c1", { method: "PATCH", headers: H, body: JSON.stringify({ notes: "tetap langganan" }) });
console.log("PATCH customer:", r.status, (await j(r)).ok);
r = await fetch(base + "/api/businesses/b2/vehicles/v1", { method: "PATCH", headers: HW, body: JSON.stringify({ plateNumber: "B 9012 GHI" }) });
console.log("PATCH vehicle dup plate (expect 409):", r.status);
r = await fetch(base + "/api/businesses/b2/vehicles/v1", { method: "PATCH", headers: HW, body: JSON.stringify({ color: "Biru" }) });
console.log("PATCH vehicle:", r.status, (await j(r)).ok);
r = await fetch(base + "/api/businesses/b2/vehicles/v1", { method: "DELETE", headers: HW });
console.log("DELETE vehicle:", r.status, (await j(r)).ok);
r = await fetch(base + "/api/businesses/b1/services/nope", { method: "PATCH", headers: H, body: JSON.stringify({ name: "x" }) });
console.log("PATCH missing service (expect 404):", r.status);
server.close();
